language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Mgr3jvmpkuR3ru1S8Y0E1kIlN7fJFPYxy0CZevru0jZlcYR7OE92BKGYmOjExiWMTLNeI9PAG6uhab22oo6glC228MOyFYJmKWFg6hLjOfH9slXHH0TQZ4oyqdqZyEODy3kJHgtye6Uv2K3TtQEQ91Gij5M9UeKkD3in2SJiIfiCOlfsj2nDv1H/Y/9HvgmIV7EUeJ4cDVvCybUiW5fwCt+9ppHtJtziDJ65VopgUoTUXne3lm0TL98veapU41yBquOPPXorHzzCA7QJaIpOdRKPb2Pkte1SmXdMHwT/MM1jZDtjhdSSk04XLFLSW0gS7GZ4bPPWBYusMOtzASlDkakFYsgkDFxBpDGHqyJGrZ5lYR9RdoDqqwgDJDU+cfZPj01yCoMkA4EgbYGtrSUgqARmwxFBNMyL7wVCLljFWIKzIY5fznyn68ARukMnjA9xnJxYdXqc38ZHrOTJiNf/z21QwhZpku4x6qLlCPqjnsKBNKGvDk8lR1o0s81U4UXLHuiXGHFUFUlmyJTMEaVgV1oZAQEElB3pG4KBjO5k6WI7pQY50rgh9rscxbgbTEH/wCleYpLFw7cCR5zoNKYR+Z2MftuIdTtDKVBtNQtCBwN16bxfY1pYL6hUN3NL06BoFslRGlv1PAAiO1fWZOAOiqogCx9uDDIK+qImq1feSWA="
env:
  secure: "Ed5PLRCpB2tIt7bHC9UTsozAj8XFWkiubNfr6MWRVPgGmg/Xo8RrpmIOUbL/Hssq51XaXOVdE/ibCJB0aFzBS3DL5TeQsmY5tLyP+toCVy/uSKyLXFgiRLPrr2ZJU31tL5t/dFUBQAgyNmc3rnf8RmBbDJaNIMPeIYYqRRdyBEBEQTNxhNhKOc6dGvERXwKDJeqzGhB9NRKv+FzYdiXGOW+brIiv/te7LnqlMTIbmMoo9z5UBtHQ8DeIIBduzHKNJkZdhhxLJu+yO2uYGbUTR+H1t/uuUuU8GMhZ+B3ZEzqMXz9CGabw1qI1PeZqwd89eZSIkk1iyKEI3YmmbwitpIS7l6k5jUMRgpAzWA2V8CL7uVlSs7sAe64S8SRKqgcufNABMVfirn8CzRZVobAKJ/jZKSWq2WNXcB2MKYNA6Whtbl3G0CG5hrrqzJlRs9W1QLG8XPblpBIrVMMGqs+wli9XbjDb7YgfuUOiJO0VTfNU1Apj8EGwu/JYE5UZMRjixd2H937ep54fvVa/31eGrm3VKxYBrfi2NKLsuldGiP9pzug8yUf4JiaFuhcck724HgMGtCt2fsjXxdgCfALW6b+BWnrdwYxxzRbJQUlMBM1SFpfniPVhDxtpB3pkf8KvEONaSXvbyrIql7fJwVXxT7nyx3GFUw5kflpzyrW4IMU="
